name: google_maps_place_picker_lks
description: A Flutter plugin which provides 'Picking Place' using Google Maps
  widget. (MB version)
version: 3.2.5
homepage: https://github.com/LoaayElkherbawy/google_maps_place_picker_lks.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.2
  google_maps_flutter: ^2.7.1
  flutter_google_maps_webservices: ^1.1.1
  http: ^1.2.2
  provider: ^6.1.2
  tuple: ^2.0.2
  uuid: ^4.5.1
  package_info_plus: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.github.zeshuaro.google_api_headers
        pluginClass: GoogleApiHeadersPlugin

false_secrets:
  - /example/lib/keys.dart
  - /example/android/app/src/main/AndroidManifest.xml
  - /example/ios/Runner/AppDelegate.swift
